on:
  push:
    branches:
      - release
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  CI:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level:
          - 29
    steps:
      - uses: actions/checkout@v3
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: 'avd-${{ matrix.api-level }}'
      - name: AVD Snapshot Caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          channel: canary
          profile: "Nexus S"
          api-level: '${{ matrix.api-level }}'
          force-avd-creation: false
          emulator-options: >-
            -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
            -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          channel: canary
          profile: "Nexus S"
          api-level: '${{ matrix.api-level }}'
          force-avd-creation: false
          emulator-options: >-
            -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
            -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
